### ISSUE TITLE
Install instructions and theme search

### ISSUE THREAD

**Issue by con-f-use** [schmittyjd/monokai-seti#123]
For the sake of new users, the read-me should have installation instructions and the theme should be in Atom's built-in theme search.

![image](https://user-images.githubusercontent.com/11145016/34357491-eed0129a-ea47-11e7-97c3-f1fcc6ae19f6.png)

Edit: I was being stupid, not getting that pic related was for searching **installed** plugins.

**Comment by schmty** [comment]
Hey @con-f-use thanks for taking the time to make an issue! I do not think there needs to be any installation instructions because installing themes on atom is so easy to do, but if you would like to have those things included I would happily accept a pull request!

As for the themes search I think you may be mistaken. The theme search is used to search within the themes that you have installed on your copy of atom. If you dont have monokai-seti installed then it won't show up in that search. However, if any new users search for the monokai-seti theme under the install tab with the themes filter highlighted then it will show up for them.

Thanks!
